### ISSUE TITLE
Turn on and wake up

### ISSUE THREAD

**Issue by b0b33140** [ayufan-rock64/android-7.1#2]
There is a problem to turn on and wake up.
I have to press the reset button to reboot, the power button does not react.

**Comment by PetruGarstea** [comment]
Hi,

quite different question, I have ordered the remote controller as well, When i press hibernate button on the remote controller it works well but when i press it again the system doesnt wake up I have to press power button on the rock64 board itself in order to wake up the system. Is it a way to fix this ?

thx

**Comment by ayufan** [comment]
This is fixed in 0.3.8.
